version: '3.8'

services:
  app:
    build: .
    container_name: introvert-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APP_ENV=development

  composer:
    image: composer:1
    volumes:
      - ./:/app
    working_dir: /app
    command: install